name: device_protocols
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  binary_data:
    #git: "https://github.com/Grabli66/BinaryData"
    path: ../BinaryData
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
